# Generated by Django 2.1.4 on 2018-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3App', '0004_hashcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('repeats', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-repeats',),
            },
        ),
        migrations.AlterModelOptions(
            name='followdata',
            options={'ordering': ('-followers',)},
        ),
    ]
