# Generated by Django 2.1.4 on 2018-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3App', '0005_auto_20181220_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('repeats', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.AlterModelOptions(
            name='timetweets',
            options={'ordering': ('-time',)},
        ),
    ]
