# Generated by Django 2.1.4 on 2018-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3App', '0006_auto_20181221_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytweets',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
